ALTER TABLE outcome_bank MODIFY COLUMN createdAt TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE outcome_bank ADD COLUMN updatedAt TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW();
ALTER TABLE outcome_bank ADD COLUMN deletedAt TIMESTAMP;